"""add notes

Revision ID: e76d08841e35
Revises: cc2b1969cbe6
Create Date: 2026-08-20 22:39:38.953184

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e76d08841e35"
down_revision: Union[str, Sequence[str], None] = "cc2b1969cbe6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), server_default="Заметка", nullable=False),
        sa.Column(
            "body",
            sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"),
            server_default="",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "conversation_notes",
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id", "note_id"),
    )
    with op.batch_alter_table("conversation_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_notes_note_id"), ["note_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_notes_note_id"))

    op.drop_table("conversation_notes")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_user_id"))

    op.drop_table("notes")
    # ### end Alembic commands ###
